version: "3.7"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://app:example@db:5432/app
    ports:
      - 8000:8000
