---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-db
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
stringData:
  database_url: "{{ required "Missing database URL scheme" .Values.db.scheme }}://{{ .Values.db.username }}:{{ .Values.db.password }}@{{ required "Missing database hostname" .Values.db.hostname }}/{{ required "Missing database name" .Values.db.database }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-db-migrations
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
stringData:
  database_url: "{{ required "Missing database URL scheme" .Values.db.scheme }}://{{ .Values.db.username }}:{{ .Values.db.password }}@{{ required "Missing database hostname" .Values.db.hostname }}/{{ required "Missing database name" .Values.db.database }}"